name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      SERVER_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Newman (Postman CLI)
        run: npm install -g newman
