name: CI

on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: self-hosted
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      SERVER_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      POSTMAN_ENVIRONMENT: ${{ secrets.POSTMAN_ENVIRONMENT }}


    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install --global newman

      - name: Run Postman tests
        run: |
          newman run Sample_APIs.postman_collection.json --environment {{ $POSTMAN_ENVIRONMENT }} --folder "Create" --iteration-data "data.csv" -r create-test-scripts.js
