name: CI

on:
  push:
    branches: main
  pull_request:
    branches: main
    
  workflow_dispatch:
    inputs:
      runJob:
        description: 'Execute all jobs'
        required: false
        default: 'true'

jobs:
  build:
    runs-on: self-hosted
    env:
      SERVER_IP: ${{ secrets.SERVER_IP }}
      SERVER_USERNAME: ${{ secrets.REMOTE_USERNAME }}
      SERVER_PASSWORD: ${{ secrets.REMOTE_PASSWORD }}
      SERVER_PORT: ${{ secrets.SERVER_PORT }}
      POSTMAN_ENVIRONMENT: ${{ secrets.POSTMAN_ENVIRONMENT }}
      API_TOKEN: ${{ secrets.YOUR_API_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js and npm
        uses: actions/setup-node@v2
        with:
          node-version: 14
          
      - name: Install Newman and reporters
        run: |
          npm install --global newman newman-reporter-html

      - name: Run Newman
        run: |
          newman run Sample_APIs.postman_collection.json --environment Sample_environment.postman_environment.json --folder "Create" --global-var "customTestScript=create-test-scripts.js"
        if: ${{ steps.RunNewman.outcome != 'success' }}
        # Mark the step as failed if the exit status is non-zero
        # continue-on-error: false

      - name: Run Manual Tests
        run: |
          node run-manual-tests.js
